name: Publish

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  build:
    name: Publish chrome webextension
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: yarn install && cd 
      - name: Build
        run: yarn build 
      - name: Zip
        run: yarn zip 
      - name: Upload & release
        uses: trmcnvn/chrome-addon@v2
        with:
          extension: lodmooidffdogioahhfhnccfpjnblcio
          zip: dist/extension.zip
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
