name: Publish

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  build:
    name: Publish chrome webextension
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install:all
      - name: Build
        run: yarn build 
      - name: Zip
        run: yarn zip 
      - name: Upload & release
        # You may pin to the exact commit or the version.
        # uses: trmcnvn/chrome-addon@7fc5a5ad3ff597dc64d6a13de7dcaa8515328be7
        uses: trmcnvn/chrome-addon@v2
        with:
          extension:  ${{ secrets.EXTENSION_ID }}
          zip: /
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
  
            client-secret: ${{ secrets.CLIENT_SECRET }}
