name: Publish

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  build:
    name: Publish chrome webextension
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install:all
      - name: Build
        run: yarn build 
      - name: Zip
        run: yarn zip 
      - name: Upload & release
        uses: Passiverecords/chrome-extension-upload-action@1.4.1
        with:
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          app-id: ${{ secrets.EXTENSION_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          file-name: ./extension.zip
          publish: False
